# Generated by Django 3.2.9 on 2021-12-14 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('createOrder', '0003_auto_20211120_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Create_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_first_name', models.CharField(max_length=25)),
                ('cust_last_name', models.CharField(max_length=25)),
                ('cust_email', models.CharField(max_length=50)),
                ('cust_phone', models.BigIntegerField(blank=True)),
                ('product_name', models.CharField(blank=True, max_length=25)),
                ('product_type', models.CharField(blank=True, max_length=25)),
                ('quantity', models.IntegerField(blank=True)),
                ('order_description', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'create_order',
            },
        ),
        migrations.RemoveField(
            model_name='order_detail',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='product_id',
        ),
        migrations.AddField(
            model_name='order_detail',
            name='job_order_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='createOrder.job_order', verbose_name='Order ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category_id',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.DO_NOTHING, to='createOrder.product_category', verbose_name='Product Category ID'),
        ),
        migrations.AlterField(
            model_name='product_category',
            name='product_category_description',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='product_category',
            name='product_category_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='order_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='createOrder.create_order', verbose_name='Order ID'),
        ),
    ]
